### ISSUE TITLE
ng serve not working

### ISSUE THREAD

**Issue by royrakesh** [cornflourblue/angular-6-registration-login-example#1]
Local workspace file ('angular.json') could not be found.

**Comment by X-Anonymous-Y** [comment]
this is not a Angular/Cli version!

use "npm start" or "npm build" instaed

**Comment by craigcampbell** [comment]
When I run npm start after install I get nothing? is it because of the port #? 

Also how hard would it be to move this to the regular angular-cli?

**Comment by X-Anonymous-Y** [comment]
That helped me to integrate angular/cli.

Use the link below

[https://github.com/angular/angular-cli](https://github.com/angular/angular-cli/issues/755#issuecomment-284317315)

**Comment by X-Anonymous-Y** [comment]
Close here please @cornflourblue

**Comment by cornflourblue** [comment]
👍
